### ISSUE TITLE
Create bot to optimize callFee on strategies 

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-cowllector#68]
# Context
Strategies have a public `harvest()` function that is responsible for earning yield. This function should be called at least once per day to provide decent value for vault users. 

There is an incentive in place for people to call the function. It is a percent of the harvested rewards and it's determined by the `callFee` variable. `callFee` starts at `50` which means that the person calling the function keeps 0.5% of the harvested rewards. 

The incentive for Beefy is to keep that number as low as possible while also getting the required service. There are currently many instances where we are overpaying for the service. 

Most of the value of compounding comes from doing it 1-3 times per day. But if harvesting is profitable then bots will do it more often, there are times where harvests happen every 6-9 seconds. This is unnecessary and signals that the `callFee` is too high for that vault at that given moment. Every $ that we can save on harvesting fees is $ that goes to the BIFI holders or the treasury instead.

The Beefy strategy contracts have a `setWithdrawalFee()` function that can decrease/increase the callFee. We are not doing much with this at the moment.
 
# Solution
Create a bot that we can run as part of the cowllector, or a standalone. It should seek to optimize the `callFee` of vaults, lower it when we're paying too much and increasing it if it's too low. 

There are many ways to do this, for example checking the harvest frequency of the past 5-10 harvests and if it's happening too often (more than once per 4h period for example) then it should decrease the `callFee` slightly.

**Comment by AllTradesz** [comment]
closing, stale

**Comment by AllTradesz** [comment]
closing, stale
