### ISSUE TITLE
Add redundancy to RPC selection when harvesting. 

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-cowllector#78]
# Description
We are looking to improve the reliability of our harvesting bot. Its objective is to make sure that we call the `harvest()` function at least every x hours. Different strategies have different harvest intervals configured. 

The script that harvests can be found at [scripts/harvest.js](https://github.com/beefyfinance/beefy-cowllector/blob/master/scripts/harvest.js). The current implementation is not very resilient. If it has troubles connecting to a particular chain's RPC, or for some reason the RPC fails it just keeps going to the next strategy.

The problem is that RPCs in some chains are pretty flaky. The idea would be to add 3-5 RPCs as options for each chain. The script would try to harvest using one of them. If it fails for an RPC issue it would select another one, until it succeeds.

# Tasks
- [ ] If a strategy harvest fails due to an RPC error, try with a different one from 3-5 options.

**Comment by AllTradesz** [comment]
closing, stale
